### ISSUE TITLE
Add looped samples back

### ISSUE THREAD

**Issue by The-Beesh-Spweesh** [chiptunecafe/0CC-SnoozeTracker#2]
I just discovered that v0.1 alpha has the ability to loop samples. v0.2 redesigned the entire UI, but tEFFx forgot about the loop checkbox!

**Comment by N-SPC700** [comment]
It's in the TODO list. Probably will rewrite the entire tracker before that, though.

**Comment by The-Beesh-Spweesh** [comment]
Also, note that v0.1 modules with looped samples load and play fine in v0.2. Even replacing the sample with another one doesn't mess with it. So basically, I have to first create a looped sample instrument in 0.1, and make the rest of the instruments and compose the song in 0.2.

**Comment by The-Beesh-Spweesh** [comment]
> It's in the TODO list. Probably will rewrite the entire tracker before that, though.

Where's the TODO list?
